# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartOrder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CryptoSwift' , '~> 0.15.0'
  pod 'SwiftyBootpay', '~> 2.1.18'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  # Pods for SmartOrder

end
